services:
  postgres:
    image: postgres
    ports:
      - "5434:5434"
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  python:
    image: python:3.10
    build: .
    command: python ./src/backend/startup.py
    volumes:
      - .:/src
    ports:
      - "8000:8000"
    depends_on:
      - postgres
