var grid = {
    nodes: [
      { id: "0", label: "1", x: 0, y: 0, size: 1, color: 'yellow' },
      { id: "1", label: "2", x: 0, y: 1, size: 1, color: 'yellow' },
      { id: "2", label: "3", x: 0, y: 2, size: 1, color: 'yellow' },
      { id: "3", label: "4", x: 0, y: 3, size: 1, color: 'yellow' },
      { id: "4", label: "5", x: 0, y: 4, size: 1, color: 'yellow' },
      { id: "5", label: "6", x: 0, y: 5, size: 1, color: 'yellow' },
      { id: "6", label: "7", x: 1, y: 0, size: 1, color: 'yellow' },
      { id: "7", label: "8", x: 1, y: 1, size: 1, color: 'yellow' },
      { id: "8", label: "9", x: 1, y: 2, size: 1, color: 'yellow' },
      { id: "9", label: "10", x: 1, y: 3, size: 1, color: 'yellow' },
      { id: "10", label: "11", x: 1, y: 4, size: 1, color: 'yellow' },
      { id: "11", label: "12", x: 1, y: 5, size: 1, color: 'yellow' },
      { id: "12", label: "13", x: 2, y: 0, size: 1, color: 'yellow' },
      { id: "13", label: "14", x: 2, y: 1, size: 1, color: 'yellow' },
      { id: "14", label: "15", x: 2, y: 2, size: 1, color: 'yellow' },
      { id: "15", label: "16", x: 2, y: 3, size: 1, color: 'yellow' },
      { id: "16", label: "17", x: 2, y: 4, size: 1, color: 'yellow' },
      { id: "17", label: "18", x: 2, y: 5, size: 1, color: 'yellow' },
      { id: "18", label: "19", x: 3, y: 0, size: 1, color: 'yellow' },
      { id: "19", label: "20", x: 3, y: 1, size: 1, color: 'yellow' },
      { id: "20", label: "21", x: 3, y: 2, size: 1, color: 'yellow' },
      { id: "21", label: "22", x: 3, y: 3, size: 1, color: 'yellow' },
      { id: "22", label: "23", x: 3, y: 4, size: 1, color: 'yellow' },
      { id: "23", label: "24", x: 3, y: 5, size: 1, color: 'yellow' },
      { id: "24", label: "25", x: 4, y: 0, size: 1, color: 'yellow' },
      { id: "25", label: "26", x: 4, y: 1, size: 1, color: 'yellow' },
      { id: "26", label: "27", x: 4, y: 2, size: 1, color: 'yellow' },
      { id: "27", label: "28", x: 4, y: 3, size: 1, color: 'yellow' },
      { id: "28", label: "29", x: 4, y: 4, size: 1, color: 'yellow' },
      { id: "29", label: "30", x: 4, y: 5, size: 1, color: 'yellow' },
      { id: "30", label: "31", x: 5, y: 0, size: 1, color: 'yellow' },
      { id: "31", label: "32", x: 5, y: 1, size: 1, color: 'yellow' },
      { id: "32", label: "33", x: 5, y: 2, size: 1, color: 'yellow' },
      { id: "33", label: "34", x: 5, y: 3, size: 1, color: 'yellow' },
      { id: "34", label: "35", x: 5, y: 4, size: 1, color: 'yellow' },
      { id: "35", label: "36", x: 5, y: 5, size: 1, color: 'yellow' },

    ],
    edges: [
      { id: "e0", source: "0", target: "1", size: 1, color: 'black' }, 
      { id: "e2", source: "0", target: "6", size: 1, color: 'black' },
      { id: "e4", source: "1", target: "7", size: 1, color: 'black' },
      { id: "e5", source: "2", target: "3", size: 1, color: 'black' },
      { id: "e3", source: "1", target: "2", size: 1, color: 'black' },
      { id: "e6", source: "2", target: "8", size: 1, color: 'black' },
      { id: "e7", source: "3", target: "4", size: 1, color: 'black' },
      { id: "e8", source: "3", target: "9", size: 1, color: 'black' },
      { id: "e9", source: "4", target: "5", size: 1, color: 'black' },
      { id: "e10", source: "4", target: "10", size: 1, color: 'black' },
      { id: "e11", source: "5", target: "11", size: 1, color: 'black' },
      { id: "e12", source: "6", target: "7", size: 1, color: 'black' },
      { id: "e13", source: "6", target: "12", size: 1, color: 'black' },
      { id: "e14", source: "7", target: "8", size: 1, color: 'black' },
      { id: "e15", source: "7", target: "13", size: 1, color: 'black' },
      { id: "e16", source: "8", target: "9", size: 1, color: 'black' },
      { id: "e17", source: "8", target: "14", size: 1, color: 'black' },
      { id: "e18", source: "9", target: "10", size: 1, color: 'black' },
      { id: "e19", source: "9", target: "15", size: 1, color: 'black' },
      { id: "e20", source: "10", target: "11", size: 1, color: 'black' },
      { id: "e21", source: "10", target: "16", size: 1, color: 'black' },
      { id: "e22", source: "11", target: "17", size: 1, color: 'black' },
      { id: "e23", source: "12", target: "13", size: 1, color: 'black' },
      { id: "e24", source: "12", target: "18", size: 1, color: 'black' },
      { id: "e25", source: "13", target: "14", size: 1, color: 'black' },
      { id: "e26", source: "13", target: "19", size: 1, color: 'black' },
      { id: "e27", source: "14", target: "15", size: 1, color: 'black' },
      { id: "e28", source: "14", target: "20", size: 1, color: 'black' },
      { id: "e29", source: "15", target: "16", size: 1, color: 'black' },
      { id: "e30", source: "15", target: "21", size: 1, color: 'black' },
      { id: "e31", source: "16", target: "17", size: 1, color: 'black' },
      { id: "e32", source: "16", target: "22", size: 1, color: 'black' },
      { id: "e33", source: "17", target: "23", size: 1, color: 'black' },
      { id: "e34", source: "18", target: "19", size: 1, color: 'black' },
      { id: "e35", source: "18", target: "24", size: 1, color: 'black' },
      { id: "e36", source: "19", target: "20", size: 1, color: 'black' },
      { id: "e37", source: "19", target: "25", size: 1, color: 'black' },
      { id: "e38", source: "20", target: "21", size: 1, color: 'black' },
      { id: "e39", source: "20", target: "26", size: 1, color: 'black' },
      { id: "e40", source: "21", target: "22", size: 1, color: 'black' },
      { id: "e41", source: "21", target: "27", size: 1, color: 'black' },
      { id: "e42", source: "22", target: "23", size: 1, color: 'black' },
      { id: "e43", source: "22", target: "28", size: 1, color: 'black' },
      { id: "e44", source: "23", target: "29", size: 1, color: 'black' },
      { id: "e45", source: "24", target: "25", size: 1, color: 'black' },
      { id: "e46", source: "24", target: "30", size: 1, color: 'black' },
      { id: "e47", source: "25", target: "26", size: 1, color: 'black' },
      { id: "e48", source: "25", target: "31", size: 1, color: 'black' },
      { id: "e49", source: "26", target: "27", size: 1, color: 'black' },
      { id: "e50", source: "26", target: "32", size: 1, color: 'black' },
      { id: "e51", source: "27", target: "28", size: 1, color: 'black' },
      { id: "e52", source: "27", target: "33", size: 1, color: 'black' },
      { id: "e53", source: "28", target: "29", size: 1, color: 'black' },
      { id: "e54", source: "28", target: "34", size: 1, color: 'black' },
      { id: "e55", source: "29", target: "35", size: 1, color: 'black' },
      { id: "e56", source: "30", target: "31", size: 1, color: 'black' },
      { id: "e58", source: "31", target: "32", size: 1, color: 'black' },
      { id: "e59", source: "32", target: "33", size: 1, color: 'black' },
      { id: "e60", source: "33", target: "34", size: 1, color: 'black' },
      { id: "e61", source: "34", target: "35", size: 1, color: 'black' },

    ]
}
var tree = {
    nodes: [
      { id: "0", label: "1", x: 0, y: 4, size: 1, color: 'yellow' },
      { id: "1", label: "2", x: -2, y: 3, size: 1, color: 'yellow' },
      { id: "2", label: "3", x: 2, y: 3, size: 1, color: 'yellow' },
      { id: "3", label: "4", x: -3, y: 2, size: 1, color: 'yellow' },
      { id: "4", label: "5", x: -1, y: 2, size: 1, color: 'yellow' },
      { id: "5", label: "6", x: 1, y: 2, size: 1, color: 'yellow' },
      { id: "6", label: "7", x: 3, y: 2, size: 1, color: 'yellow' },
      { id: "7", label: "8", x: -3.5, y: 1, size: 1, color: 'yellow' },
      { id: "8", label: "9", x: -2.5, y: 1, size: 1, color: 'yellow' },
      { id: "9", label: "10", x: -1.5, y: 1, size: 1, color: 'yellow' },
      { id: "10", label: "11", x: -.5, y: 1, size: 1, color: 'yellow' },
      { id: "11", label: "12", x: .5, y: 1, size: 1, color: 'yellow' },
      { id: "12", label: "13", x: 1.5, y: 1, size: 1, color: 'yellow' },
      { id: "13", label: "14", x: 2.5, y: 1, size: 1, color: 'yellow' },
      { id: "14", label: "15", x: 3.5, y: 1, size: 1, color: 'yellow' }
    ],
    edges: [
      { id: "e0", source: "0", target: "1", color: '#282c34', size:20 },
      { id: "e1", source: "0", target: "2", color: '#282c34', size:20},
      { id: "e2", source: "1", target: "3", color: '#282c34', size:20},
      { id: "e3", source: "1", target: "4", color: '#282c34', size:20},
      { id: "e4", source: "2", target: "5", color: '#282c34', size:20},
      { id: "e5", source: "2", target: "6", color: '#282c34', size:20},
      { id: "e6", source: "3", target: "7", color: '#282c34', size:20},
      { id: "e7", source: "3", target: "8", color: '#282c34', size:20},
      { id: "e8", source: "4", target: "9", color: '#282c34', size:20},
      { id: "e9", source: "4", target: "10", color: '#282c34', size:20},
      { id: "e10", source: "5", target: "11", color: '#282c34', size:20},
      { id: "e11", source: "5", target: "12", color: '#282c34', size:20},
      { id: "e12", source: "6", target: "13", color: '#282c34', size:20},
      { id: "e13", source: "6", target: "14", color: '#282c34', size:20}
    ]
}